development:
  adapter: postgresql
  username: postgres
  database: railsyard2_test

production:
    adapter: postgresql
    username: postgres
    database: railsyard2_test

test:
    adapter: postgresql
    username: postgres
    database: railsyard2_test