mysql: &mysql
  adapter: mysql2
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
#  socket: /tmp/mysql.sock
  charset: utf8
  collation: utf8_bin

postgres: &postgres
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password:
  encoding: unicode


common: &common
  # Choose one of the following
  <<: *mysql
  #<<: *postgres


development:
  <<: *common
  database: railsyard2_development

production:
  <<: *common
  database: railsyard2_production

test:
  <<: *common
  database: railsyard2_test