# !!! Config inside config/evironments/development.rb and config/environments/production.rb  !!!

#OLD

# development:
#     delivery_method: :smtp
#     smtp_settings:
#         address: 127.0.0.1
#         port: 25
#         domain: example.com
#         authentication: :login
#         user_name: "info@example.com"
#         password: "changeme"

# development:
#   :address: smtp.server.com
#   :port: 25
#   :authentication: plain
#   :user_name: user
#   :password: pass
# 
# production:
#   :address: smtp.server.com
#   :port: 25
#   :authentication: plain
#   :user_name: user
#   :password: pass